spring:
  application:
    name: HarasyProject
  datasource:
    url: jdbc:mysql://swp-fa24.ctgg040kah0a.ap-east-1.rds.amazonaws.com:3306/Harasy
    username: user1
    password: password1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  mail:
    host: smtp.gmail.com
    port: 587
    username: ThinhNgyenCTH@gmail.com
    password: xjprckvxgpxgbnna
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: redis-17137.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 17137
      password: LIBPmf3oGvv9TNJhviRbNiEtPdx9K0zs
logging:
  level:
    org:
      springframework:
        security: debug
jwt:
  signerKey: "u9XmfDeNsjC8ZrdM1Ig745GJ01RfRPY0sg44Z0oUJlHa2cOZ0vy5ADqKmn2c61nE"
  validDuration: 60
  refreshTokenDuration: 2592000
cloudinary:
  cloud-name: "dane9zvkx"
  api-key: "812732431165188"
  api-secret: "tndHqcDi607JkZViukHBIHvgLO4"